data_row = [{'offchain_id': '56e376ae5fc02922f484822665ff2015', 'onchain_id': 36,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/82',
             'title': 'TGVhcm4tdG8tRWFybiBFZHVjYXRpb24gYm90IGJ5IE1lbGtEQU8=', 'type': 'request-for-funding',
             'state': 'accepted', 'review_end_timestamp': '2023-06-13T14:40:18.100Z',
             'voting_end_timestamp': '2023-06-20T14:40:18.100Z', 'timelock_end_timestamp': '2023-06-23T14:40:18.100Z',
             'execution_timestamp': None, 'expiration_timestamp': '2023-07-23T14:40:18.100Z',
             'onchain_creation_timestamp': '2023-06-12T14:14:26.887Z',
             'offchain_creation_timestamp': '2023-05-10T00:36:15.695Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 32, 'votes_amount_accept': 4, 'votes_amount_reject': 0,
             'votes_amount_abstain': 1, 'hotness': 0.0},
            {'offchain_id': '7a385d44dc9d9f33e52f2b26772a9c98', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/86',
             'title': 'VXBsaWZ0IENvdXBvbmluZyBmb3IgTkVP', 'type': 'request-for-funding', 'state': 'discussion',
             'review_end_timestamp': None, 'voting_end_timestamp': None, 'timelock_end_timestamp': None,
             'execution_timestamp': None, 'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-06-23T13:18:55.619Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 0, 'votes_amount_accept': None, 'votes_amount_reject': None,
             'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '9850bee54056a2dfe19ff109d2c228f0', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/85',
             'title': 'TmVvIEhhY2thdGhvbiBvbiBCbG9ja2NoYWluIENvbnZlcnNhdGlvbiBhbmQgRGVtbw==',
             'type': 'request-for-funding', 'state': 'discussion', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-06-12T16:54:14.179Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 1, 'votes_amount_accept': None, 'votes_amount_reject': None,
             'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '06570821205ce22a3fdee2ba19eb550a', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/84', 'title': 'TmVvIEV1cm8gQm9uZHM=',
             'type': 'request-for-funding', 'state': 'discussion', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-06-08T21:38:28.146Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 1, 'votes_amount_accept': None, 'votes_amount_reject': None,
             'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'b70113d52d8443b210138205f3356794', 'onchain_id': 33,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/20',
             'title': 'QW4gYW5hbHlzaXMgb2YgdGhlIHR3byB0b2tlbnMgTmVvIEVjb25vbXkgKE1pbGVzdG9uZSAyKQ==',
             'type': 'request-for-funding', 'state': 'expired', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': '2023-06-07T16:09:14.659Z',
             'onchain_creation_timestamp': '2023-05-08T16:09:14.659Z',
             'offchain_creation_timestamp': '2022-08-22T15:50:09.640Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 19, 'votes_amount_accept': 0, 'votes_amount_reject': 0,
             'votes_amount_abstain': 0, 'hotness': 0.0},
            {'offchain_id': '7f8cd21dbf512efc3937f814a178dcc0', 'onchain_id': 35,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/73',
             'title': 'UGl4dWRpIHdpdGggTmVvRlMgaW50ZWdyYXRpb24uIE1pbGVzdG9uZSAxOiBMYXVuY2hpbmcgY29sbGVjdGlvbiAmIHRoZSBnYW1lIHdpdGggTkVPLg==',
             'type': 'request-for-funding', 'state': 'on-chain', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': '2023-06-29T14:45:06.134Z',
             'onchain_creation_timestamp': '2023-05-30T14:45:06.134Z',
             'offchain_creation_timestamp': '2023-03-27T01:45:10.378Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 28, 'votes_amount_accept': 0, 'votes_amount_reject': 0,
             'votes_amount_abstain': 0, 'hotness': 0.0},
            {'offchain_id': '2401cd3c8bd6f798ed76bacc325f0a8d', 'onchain_id': 32,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/77',
             'title': 'TmVvRmxvdzogQW5hbHl0aWNzIERhc2hib2FyZCBmb3IgRXhwbG9yaW5nIEFjdGl2aXRpZXMgaW4gTkVP',
             'type': 'request-for-funding', 'state': 'expired', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': '2023-05-29T22:52:01.797Z',
             'onchain_creation_timestamp': '2023-04-29T22:52:01.797Z',
             'offchain_creation_timestamp': '2023-04-09T20:55:07.219Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 7, 'votes_amount_accept': 0, 'votes_amount_reject': 0,
             'votes_amount_abstain': 0, 'hotness': 0.0},
            {'offchain_id': '5f5ac71b7c87bd00b1d33481bbc675e6', 'onchain_id': 34,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/81',
             'title': 'UmVtb3ZhbCBvZiBJbmFjdGl2ZSBNZW1iZXI=', 'type': 'remove-member', 'state': 'executed',
             'review_end_timestamp': '2023-05-10T19:43:13.868Z', 'voting_end_timestamp': '2023-05-17T19:43:13.868Z',
             'timelock_end_timestamp': '2023-05-20T19:43:13.868Z', 'execution_timestamp': '2023-05-20T22:01:03.347Z',
             'expiration_timestamp': '2023-06-19T19:43:13.868Z',
             'onchain_creation_timestamp': '2023-05-09T15:23:07.739Z',
             'offchain_creation_timestamp': '2023-05-09T15:14:08.250Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 5, 'votes_amount_accept': 8, 'votes_amount_reject': 0,
             'votes_amount_abstain': 0, 'hotness': 0.0},
            {'offchain_id': 'b286170576c2268550b81a157690135f', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/83',
             'title': 'R3JlbmFkZW1pbmlzIChNaWxlc3RvbmUp', 'type': 'request-for-funding', 'state': 'cancelled',
             'review_end_timestamp': None, 'voting_end_timestamp': None, 'timelock_end_timestamp': None,
             'execution_timestamp': None, 'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-05-19T04:12:09.627Z',
             'offchain_cancellation_timestamp': '2023-05-23T01:06:49.842Z', 'offchain_comments_count': 7,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'd62ce6cee1e13e72e5ba95fc5ef47181', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/80',
             'title': 'V0VCM0RFViBoZWxwaW5nIE5lbyBncm93dGggaW4gTGF0aW4gQW1lcmljYQ==', 'type': 'request-for-funding',
             'state': 'discussion', 'review_end_timestamp': None, 'voting_end_timestamp': None,
             'timelock_end_timestamp': None, 'execution_timestamp': None, 'expiration_timestamp': None,
             'onchain_creation_timestamp': None, 'offchain_creation_timestamp': '2023-05-05T17:57:23.658Z',
             'offchain_cancellation_timestamp': None, 'offchain_comments_count': 16, 'votes_amount_accept': None,
             'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '24e3415c18c4cc7222a5734f5b9a9e67', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/79',
             'title': 'Q09aIC0gVzNCM1dBVjMgSW50ZXJuZXRsZXNzIGNvbm5lY3Rpb25z', 'type': 'request-for-funding',
             'state': 'discussion', 'review_end_timestamp': None, 'voting_end_timestamp': None,
             'timelock_end_timestamp': None, 'execution_timestamp': None, 'expiration_timestamp': None,
             'onchain_creation_timestamp': None, 'offchain_creation_timestamp': '2023-05-02T20:06:33.300Z',
             'offchain_cancellation_timestamp': None, 'offchain_comments_count': 8, 'votes_amount_accept': None,
             'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'c151f5ba6f0256dadaa904b2974e3b83', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/78',
             'title': 'UmVuZXdlZCBpT1MgU0RLIChNaWxlc3RvbmUgMyBvZiAzKQ==', 'type': 'request-for-funding',
             'state': 'discussion', 'review_end_timestamp': None, 'voting_end_timestamp': None,
             'timelock_end_timestamp': None, 'execution_timestamp': None, 'expiration_timestamp': None,
             'onchain_creation_timestamp': None, 'offchain_creation_timestamp': '2023-04-27T18:16:02.835Z',
             'offchain_cancellation_timestamp': None, 'offchain_comments_count': 18, 'votes_amount_accept': None,
             'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'ddd62c72db57fa5f0a0f97fe011903e3', 'onchain_id': 31,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/68',
             'title': 'S0lLQSBUb2tlbiBTb2Z0d2FyZSBDb21wYW55LS0gYSBjb21tdW5pdHkgb3duZWQgc29mdHdhcmUgY29tcGFueSwgcG93ZXJlZCBieSBORU8gKEJVSUxEIEJBQ0tFTkQgSU5GUkFTVFJVQ1RVUkUgQU5EIEZJUlNUIEFQUFMp',
             'type': 'request-for-funding', 'state': 'expired', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': '2023-04-23T16:26:15.227Z',
             'onchain_creation_timestamp': '2023-03-24T16:26:15.227Z',
             'offchain_creation_timestamp': '2023-03-21T20:03:20.510Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 6, 'votes_amount_accept': 0, 'votes_amount_reject': 0,
             'votes_amount_abstain': 0, 'hotness': 0.0},
            {'offchain_id': '937e330f476b00d378a22f532be0fc2a', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/75',
             'title': 'VHJhbnNhY3RpbmcgTkVPIG9uIFBhc3NNZUNhc2g=', 'type': 'request-for-funding', 'state': 'discussion',
             'review_end_timestamp': None, 'voting_end_timestamp': None, 'timelock_end_timestamp': None,
             'execution_timestamp': None, 'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-04-05T19:40:39.184Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 12, 'votes_amount_accept': None, 'votes_amount_reject': None,
             'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '7a1bab8b2461693eee24fbbd209091ac', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/74', 'title': 'TkVPIENSRVczIEFDQ09VTlQ=',
             'type': 'request-for-funding', 'state': 'discussion', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-28T09:22:08.221Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 10, 'votes_amount_accept': None, 'votes_amount_reject': None,
             'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '42e93504b99c63c7a559a8908f850b05', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/72',
             'title': 'UGl4dWRpIGNvbWJpbmVzIHRyYWRpdGlvbmFsIGJvYXJkIGdhbWVzIHdpdGggYmxvY2tjaGFpbiB0ZWNobm9sb2d5IHRvIGludHJvZHVjZSBpdCB0byBtaWxsaW9ucyBvZiBXRUIyIHVzZXJzIHdvcmxkd2lkZS4=',
             'type': 'request-for-funding', 'state': 'cancelled', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-27T01:17:36.634Z',
             'offchain_cancellation_timestamp': '2023-03-27T01:45:35.119Z', 'offchain_comments_count': 1,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'e9fecd88b800e72aeda5f304a6606f18', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/71', 'title': 'UGl4dWRp',
             'type': 'request-for-funding', 'state': 'cancelled', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-27T00:48:03.574Z',
             'offchain_cancellation_timestamp': '2023-03-27T01:18:40.348Z', 'offchain_comments_count': 1,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'b64c10702823cfd34caf858146c62c7b', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/70',
             'title': 'bW90b0RFWCAtIGEgQmxvY2tjaGFpbiBHYW1lLCBpbiB3aGljaCB1c2VycyBwYXJ0aWNpcGF0ZSBpbiBtb3RvcmN5Y2xlIHJhY2VzLCAgZGV2ZWxvcCB0aGVpciByaWRlcnMgYW5kIGltcHJvdmUgaGlnaC1zcGVlZCB0cmFja3Mu',
             'type': 'request-for-funding', 'state': 'discussion', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-22T18:40:14.834Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 0, 'votes_amount_accept': None, 'votes_amount_reject': None,
             'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'fbd164449fbe654edf6935714bc5713d', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/69',
             'title': 'T3BlbkJpU2VhLmlvIC0gR2FtZSBTdHVkaW8gYW5kIE11bHRpLWNoYWluIE5GVCBhdWN0aW9ucw==',
             'type': 'request-for-funding', 'state': 'discussion', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-22T18:32:47.083Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 0, 'votes_amount_accept': None, 'votes_amount_reject': None,
             'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '738656940a1de3619a1126d06014501a', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/67', 'title': 'Q3JldzMgTmVvIEFjY291bnQ=',
             'type': 'request-for-funding', 'state': 'cancelled', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-20T10:20:18.525Z',
             'offchain_cancellation_timestamp': '2023-03-28T09:45:05.741Z', 'offchain_comments_count': 4,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '68e31941495bf847318eba8083669589', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/66',
             'title': 'S0lLQSBTb2Z0d2FyZSBDb21wYW55IC0tIGEgY29tbXVuaXR5IG93bmVkLCBjdXJyZW5jeSBhZ25vc3RpYywgZ2xvYmFsIHdlYjMgY29tcGFueSBwb3dlcmVkIGJ5IE5FTw==',
             'type': 'request-for-funding', 'state': 'cancelled', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-19T18:19:32.680Z',
             'offchain_cancellation_timestamp': '2023-03-21T20:04:46.518Z', 'offchain_comments_count': 4,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '3e9b27ba37582a8a8bc687218507b536', 'onchain_id': 30,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/62',
             'title': 'QWNjZWxlcmF0aW5nIHRoZSBhZG9wdGlvbiBvZiBOZW8gZWNvbm9teSB3aXRoIHBhcnRpY2lwYXRvcnkgZ292ZXJuYW5jZQ==',
             'type': 'request-for-funding', 'state': 'executed', 'review_end_timestamp': '2023-03-03T16:23:02.069Z',
             'voting_end_timestamp': '2023-03-10T16:23:02.069Z', 'timelock_end_timestamp': '2023-03-13T16:23:02.069Z',
             'execution_timestamp': '2023-03-13T20:01:22.187Z', 'expiration_timestamp': '2023-04-12T16:23:02.069Z',
             'onchain_creation_timestamp': '2023-03-03T13:10:54.964Z',
             'offchain_creation_timestamp': '2023-02-08T11:56:57.024Z', 'offchain_cancellation_timestamp': None,
             'offchain_comments_count': 30, 'votes_amount_accept': 4, 'votes_amount_reject': 1,
             'votes_amount_abstain': 1, 'hotness': 0.0},
            {'offchain_id': 'df7c3984c109bb5e49da79a10c09c24e', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/65',
             'title': 'T3BlbkJpU2VhLmlvIC0gR2FtZSBTdHVkaW8gYW5kIE11bHRpLWNoYWluIE5GVCBhdWN0aW9ucw==',
             'type': 'request-for-funding', 'state': 'cancelled', 'review_end_timestamp': None,
             'voting_end_timestamp': None, 'timelock_end_timestamp': None, 'execution_timestamp': None,
             'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-03-13T14:59:14.985Z',
             'offchain_cancellation_timestamp': '2023-03-27T17:11:38.859Z', 'offchain_comments_count': 9,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': 'a69a80db40706cbfef52262b71b0ff3c', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/64',
             'title': 'SW1wbGVtZW50ZSBOZW8gVmlydHVhbCBNYWNoaW5lIGluIFJ1c3Q=', 'type': 'request-for-funding',
             'state': 'cancelled', 'review_end_timestamp': None, 'voting_end_timestamp': None,
             'timelock_end_timestamp': None, 'execution_timestamp': None, 'expiration_timestamp': None,
             'onchain_creation_timestamp': None, 'offchain_creation_timestamp': '2023-03-11T04:48:23.861Z',
             'offchain_cancellation_timestamp': '2023-03-12T19:14:43.078Z', 'offchain_comments_count': 10,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0},
            {'offchain_id': '3efa41c8a849853650e4b06821a4c57e', 'onchain_id': None,
             'discussion_url': 'https://github.com/AxLabs/grantshares/issues/63',
             'title': 'TmVvLUtlbnlhIENvbW11bml0eQ==', 'type': 'request-for-funding', 'state': 'cancelled',
             'review_end_timestamp': None, 'voting_end_timestamp': None, 'timelock_end_timestamp': None,
             'execution_timestamp': None, 'expiration_timestamp': None, 'onchain_creation_timestamp': None,
             'offchain_creation_timestamp': '2023-02-28T21:33:19.292Z',
             'offchain_cancellation_timestamp': '2023-03-03T12:39:23.615Z', 'offchain_comments_count': 3,
             'votes_amount_accept': None, 'votes_amount_reject': None, 'votes_amount_abstain': None, 'hotness': 0.0}]

good_list = [{'id': '56e376ae5fc02922f484822665ff2015', 'name_post': 'Learn-to-Earn Education bot by MelkDAO',
              'date_post': '10.05.23', 'link': 'https://grantshares.io/app/details/56e376ae5fc02922f484822665ff2015',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/82', 'name_them': 'request-for-funding'},
             {'id': '7a385d44dc9d9f33e52f2b26772a9c98', 'name_post': 'Uplift Couponing for NEO',
              'date_post': '23.06.23', 'link': 'https://grantshares.io/app/details/7a385d44dc9d9f33e52f2b26772a9c98',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/86', 'name_them': 'request-for-funding'},
             {'id': '9850bee54056a2dfe19ff109d2c228f0',
              'name_post': 'Neo Hackathon on Blockchain Conversation and Demo', 'date_post': '12.06.23',
              'link': 'https://grantshares.io/app/details/9850bee54056a2dfe19ff109d2c228f0',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/85', 'name_them': 'request-for-funding'},
             {'id': '06570821205ce22a3fdee2ba19eb550a', 'name_post': 'Neo Euro Bonds', 'date_post': '08.06.23',
              'link': 'https://grantshares.io/app/details/06570821205ce22a3fdee2ba19eb550a',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/84', 'name_them': 'request-for-funding'},
             {'id': '5f5ac71b7c87bd00b1d33481bbc675e6', 'name_post': 'Removal of Inactive Member',
              'date_post': '09.05.23', 'link': 'https://grantshares.io/app/details/5f5ac71b7c87bd00b1d33481bbc675e6',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/81', 'name_them': 'remove-member'},
             {'id': 'b286170576c2268550b81a157690135f', 'name_post': 'Grenademinis (Milestone)',
              'date_post': '19.05.23', 'link': 'https://grantshares.io/app/details/b286170576c2268550b81a157690135f',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/83', 'name_them': 'request-for-funding'},
             {'id': 'd62ce6cee1e13e72e5ba95fc5ef47181', 'name_post': 'WEB3DEV helping Neo growth in Latin America',
              'date_post': '05.05.23', 'link': 'https://grantshares.io/app/details/d62ce6cee1e13e72e5ba95fc5ef47181',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/80', 'name_them': 'request-for-funding'},
             {'id': '24e3415c18c4cc7222a5734f5b9a9e67', 'name_post': 'COZ - W3B3WAV3 Internetless connections',
              'date_post': '02.05.23', 'link': 'https://grantshares.io/app/details/24e3415c18c4cc7222a5734f5b9a9e67',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/79', 'name_them': 'request-for-funding'},
             {'id': 'c151f5ba6f0256dadaa904b2974e3b83', 'name_post': 'Renewed iOS SDK (Milestone 3 of 3)',
              'date_post': '27.04.23', 'link': 'https://grantshares.io/app/details/c151f5ba6f0256dadaa904b2974e3b83',
              'link_git': 'https://github.com/AxLabs/grantshares/issues/78', 'name_them': 'request-for-funding'}]
